src/objects/Effort_Information__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effort_on_Date__c</fullName>
        <label>Effort on Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Stories__c</referenceTo>
        <relationshipLabel>Effort Informations</relationshipLabel>
        <relationshipName>Effort_Informations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Effort Information</label>
    <nameField>
        <label>Effort Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Effort Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User_Stories__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effort_on_Date__c</fullName>
        <label>Effort on Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Effort_Covered__c</fullName>
        <label>Total Effort Covered</label>
        <summarizedField>Effort_Information__c.Effort_on_Date__c</summarizedField>
        <summaryForeignKey>Effort_Information__c.User_Story__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Effort_Req__c</fullName>
        <label>Total Effort Req</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tracker</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <label>User Stories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TrackerUserStoryController.cls
public class TrackerUserStoryController
{

public List<User_Stories__c> UserStoryRecord{get; set;}
public Id idOfUserStory {get; set;}
public User_Stories__c UserStory;
public Effort_Information__c EffortRecord;


public TrackerUserStoryController (ApexPages.StandardController stdController)
{

UserStoryRecord  = new List<User_Stories__c> ();

Id currentUserId = UserInfo.getUserId();

UserStoryRecord  = [select id, Name, Total_Effort_Req__c, Total_Effort_Covered__c, Tracker__c, (select id, Name, Date__c, Effort_on_Date__c from Effort_Informations__r ORDER BY Date__c ASC) from User_Stories__c where Tracker__c =: currentUserId];

}

public pagereference save ()
{
update UserStoryRecord;
return null;

}

public pagereference cancel ()
{
return null;

}





public pagereference datasave()
{
    UserStory = [select id, Name, Total_Effort_Req__c, Total_Effort_Covered__c, Tracker__c from User_Stories__c where Id =: idOfUserStory];

if(UserStory!=null)
        update UserStory;
        
        return null;
}

}