src/objects/Effort_Information__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effort_on_Date__c</fullName>
        <label>Effort on Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Stories__c</referenceTo>
        <relationshipLabel>Effort Informations</relationshipLabel>
        <relationshipName>Effort_Informations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Effort Information</label>
    <nameField>
        <label>Effort Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Effort Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User_Stories__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effort_on_Date__c</fullName>
        <label>Effort on Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <label>User Stories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NewEffortController.cls
public class NewEffortController {
    
public User_Stories__c UserStoryObj;
public Effort_Information__c EffortInfoObj;    
public Boolean refreshPage {get;set;}
Public String UserSoryId{get;set;}
 

public NewEffortController (ApexPages.StandardController controller)
{

UserSoryId    = ApexPages.CurrentPage().getParameters().get('Id');

UserStoryObj = (User_Stories__c)controller.getRecord();

 
}
public void NewEffort()
{
try
{
    EffortInfoObj = new Effort_Information__c();
if(UserStoryObj!=null)
{
EffortInfoObj.Name = 'Effort on '+UserStoryObj.Date__c;   
EffortInfoObj.User_Story__c = UserSoryId;
EffortInfoObj.Effort_on_Date__c = UserStoryObj.Effort_on_Date__c;
EffortInfoObj.Date__c = UserStoryObj.Date__c;    
insert EffortInfoObj;
}
else
{
system.debug('The object is null'); 
}
refreshPage=true;
}catch(Exception E)
{
system.debug('The following exception has occurred: ' + E.getMessage());
}

}


}